### ISSUE TITLE
Party Settings

### ISSUE THREAD

**Issue by Dominik48N** [Dominik48N/party-system#2]
It should be possible for a player to set whether he would like to receive party requests, whether he would like to receive notifications for party joins and leaves and whether he would like to be able to write or receive messages in the party chat.

It should also be possible to deactivate the function if you do not want to use the function.
If you do not use a function that requires a database, no connection to the database will be established when using the plugin.

Various database systems should be available for this. A few examples of database systems that could be supported:
* [MongoDB](https://www.mongodb.com)
* [PostgreSQL](https://www.postgresql.org)
* [MariaDB](https://mariadb.org)

**Comment by PhantomClone** [comment]
Flyway support would be nice
